services:
  db:
    container_name: pdv
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432

api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdv-api
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db